# Generated by Django 6.0.5 on 2026-06-26 06:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RoadRace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CompletedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('caption', models.TextField(blank=True, null=True)),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_builds', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BuildModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='model_images/gallery/')),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='modeldatabase.completedmodel')),
            ],
        ),
        migrations.CreateModel(
            name='CarManufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='models', to='modeldatabase.country')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ModelKit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('totalviews', models.PositiveIntegerField(default=0)),
                ('yearoftool', models.PositiveIntegerField(blank=True, default=2000, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2026)])),
                ('modelyear', models.PositiveIntegerField(default=2000, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2026)])),
                ('descriptionInput', models.TextField(blank=True, null=True)),
                ('descriptionReport', models.BooleanField(default=False)),
                ('reportReason', models.TextField(blank=True, null=True)),
                ('coverimage', models.ImageField(blank=True, null=True, upload_to='model_images/cover')),
                ('status', models.CharField(choices=[('P', 'Pending'), ('A', 'Approved'), ('R', 'Rejected')], default='P', max_length=1)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('bodytype', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='models', to='modeldatabase.bodytype')),
                ('carmanufacturer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='models', to='modeldatabase.carmanufacturer')),
                ('detail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='models', to='modeldatabase.detail')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='models', to='modeldatabase.manufacturer')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('roadrace', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='models', to='modeldatabase.roadrace')),
                ('scale', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='models', to='modeldatabase.scale')),
            ],
        ),
        migrations.AddField(
            model_name='completedmodel',
            name='model_kit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='builds', to='modeldatabase.modelkit'),
        ),
        migrations.CreateModel(
            name='TipIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_tips', to=settings.AUTH_USER_MODEL)),
                ('model_kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tips', to='modeldatabase.modelkit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='completedmodel',
            constraint=models.UniqueConstraint(fields=('model_kit', 'user'), name='unique_user_completed_model'),
        ),
    ]
