# Generated by Django 6.0.1 on 2026-02-05 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeldatabase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='dailyviews',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='model',
            name='totalviews',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
