# Generated by Django 6.0.1 on 2026-02-05 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeldatabase', '0002_model_dailyviews_model_totalviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='scale',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.CreateModel(
            name='ModelImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='model_images/gallery/')),
                ('model_kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='modeldatabase.model')),
            ],
        ),
    ]
