# Generated by Django 6.0.1 on 2026-02-05 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modeldatabase', '0004_model_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='model',
            old_name='image',
            new_name='coverimage',
        ),
    ]
