# Generated by Django 6.0.1 on 2026-02-05 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeldatabase', '0005_rename_image_model_coverimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='modelyear',
            field=models.PositiveIntegerField(default=1950),
        ),
        migrations.AddField(
            model_name='model',
            name='yearoftool',
            field=models.PositiveIntegerField(default=1950),
        ),
    ]
