# Generated by Django 6.0.1 on 2026-02-13 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeldatabase', '0006_model_modelyear_model_yearoftool'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarManufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='models', to='modeldatabase.country')),
            ],
        ),
        migrations.CreateModel(
            name='ModelKit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('dailyviews', models.PositiveIntegerField(default=0)),
                ('totalviews', models.PositiveIntegerField(default=0)),
                ('yearoftool', models.PositiveIntegerField(default=1950)),
                ('modelyear', models.PositiveIntegerField(default=1950)),
                ('scale', models.CharField(blank=True, max_length=6, null=True)),
                ('coverimage', models.ImageField(blank=True, null=True, upload_to='model_images/cover')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='models', to='modeldatabase.manufacturer')),
            ],
        ),
        migrations.AlterField(
            model_name='modelimages',
            name='model_kit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='modeldatabase.modelkit'),
        ),
        migrations.DeleteModel(
            name='Model',
        ),
    ]
