# Generated by Django 6.0.1 on 2026-02-13 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeldatabase', '0007_country_manufacturer_carmanufacturer_modelkit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelkit',
            name='carmanufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='models', to='modeldatabase.carmanufacturer'),
        ),
        migrations.AlterField(
            model_name='modelkit',
            name='modelyear',
            field=models.PositiveIntegerField(default=1900),
        ),
    ]
