# Generated by Django 6.0.1 on 2026-02-13 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeldatabase', '0008_modelkit_carmanufacturer_alter_modelkit_modelyear'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelkit',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
