# Generated by Django 6.0.1 on 2026-02-17 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeldatabase', '0010_bodytype_modelkit_bodytype'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoadRace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='modelkit',
            name='roadrace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='models', to='modeldatabase.roadrace'),
        ),
    ]
