# Generated by Django 6.0.1 on 2026-03-01 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modeldatabase', '0012_detail_modelkit_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelkit',
            name='dailyviews',
        ),
    ]
