# Generated by Django 6.0.1 on 2026-03-23 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modeldatabase', '0014_scale_modelkit_rejection_reason_modelkit_status_and_more'),
        ('modeldatabase', '0015_scale_alter_modelkit_scale'),
    ]

    operations = [
    ]
