# Generated by Django 6.0.1 on 2026-03-23 00:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeldatabase', '0016_merge_20260323_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelkit',
            name='bodytype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='models', to='modeldatabase.bodytype'),
        ),
        migrations.AlterField(
            model_name='modelkit',
            name='carmanufacturer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='models', to='modeldatabase.carmanufacturer'),
        ),
        migrations.AlterField(
            model_name='modelkit',
            name='detail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='models', to='modeldatabase.detail'),
        ),
        migrations.AlterField(
            model_name='modelkit',
            name='modelyear',
            field=models.PositiveIntegerField(default=2000, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2026)]),
        ),
        migrations.AlterField(
            model_name='modelkit',
            name='roadrace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='models', to='modeldatabase.roadrace'),
        ),
        migrations.AlterField(
            model_name='modelkit',
            name='scale',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='models', to='modeldatabase.scale'),
        ),
        migrations.AlterField(
            model_name='modelkit',
            name='yearoftool',
            field=models.PositiveIntegerField(blank=True, default=2000, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2026)]),
        ),
    ]
