# Generated by Django 6.0.1 on 2026-03-23 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeldatabase', '0017_alter_modelkit_bodytype_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bodytype',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='carmanufacturer',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='manufacturer',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='scale',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='modelkit',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
