# Generated by Django 6.0.1 on 2026-03-26 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeldatabase', '0018_alter_bodytype_options_alter_carmanufacturer_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelkit',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Approved'), ('R', 'Rejected')], default='P', max_length=1),
        ),
    ]
