# Generated by Django 6.0.1 on 2026-05-27 04:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeldatabase', '0020_tipissue'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tipissue',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_tips', to=settings.AUTH_USER_MODEL),
        ),
    ]
