# Generated by Django 6.0.5 on 2026-05-28 04:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeldatabase', '0021_tipissue_likes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('caption', models.TextField(blank=True, null=True)),
                ('model_kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='builds', to='modeldatabase.modelkit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BuildModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='model_images/gallery/')),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='modeldatabase.completedmodel')),
            ],
        ),
        migrations.DeleteModel(
            name='ModelImages',
        ),
        migrations.AddConstraint(
            model_name='completedmodel',
            constraint=models.UniqueConstraint(fields=('model_kit', 'user'), name='unique_user_completed_model'),
        ),
    ]
