# Generated by Django 6.0.5 on 2026-05-29 04:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeldatabase', '0022_completedmodel_buildmodels_delete_modelimages_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='buildmodels',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_builds', to=settings.AUTH_USER_MODEL),
        ),
    ]
