# Generated by Django 6.0.5 on 2026-05-29 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modeldatabase', '0024_remove_buildmodels_likes_completedmodel_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelkit',
            name='description',
        ),
    ]
