# Generated by Django 6.0.5 on 2026-05-30 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeldatabase', '0025_remove_modelkit_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelkit',
            name='descriptionInput',
            field=models.TextField(blank=True, null=True),
        ),
    ]
