# Generated by Django 6.0.5 on 2026-06-05 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeldatabase', '0026_modelkit_descriptioninput'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelkit',
            name='descriptionReport',
            field=models.BooleanField(default=False),
        ),
    ]
