# Generated by Django 6.0.5 on 2026-06-05 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeldatabase', '0027_modelkit_descriptionreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelkit',
            name='reportReason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
