# Generated by Django 6.0.5 on 2026-06-12 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_postreplies_created_at_postreplies_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postreplies',
            name='likes',
        ),
    ]
