# Generated by Django 6.0.5 on 2026-06-18 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_tags_post_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tags',
            name='slug',
        ),
    ]
