# Generated by Django 6.0.5 on 2026-06-18 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_remove_tags_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tagged', to='forum.tags'),
        ),
    ]
