# Generated by Django 6.0.5 on 2026-06-20 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpcenter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertipprogress',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
