# Generated by Django 6.0.5 on 2026-06-25 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpcenter', '0002_usertipprogress_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='beginnertip',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='beginner_tips/gallery/'),
        ),
    ]
